---
title: "LakeMetab_ModelPrep"
author: "Kelly Loria"
date: '2024-01-24'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
options(width = 200)
knitr::opts_chunk$set(include = TRUE, message = FALSE, warning = FALSE, fig.height = 4, fig.width = 8)
```


### This is the second of two organizational scripts to look at DO output as a timesieries. 

```{r, results = "hide"}
lapply(c("plyr","dplyr","ggplot2","cowplot","lubridate",
         "tidyverse","data.table","xts","dygraphs",
         "nrlmetab","cowplot", "rstan"), require, character.only=T)

source("./saved_fxns/k.vachon.R")
source("./saved_fxns/k600.2.kGAS.R")
source("./saved_fxns/getSchmidt.R")
```

Reading in processed data from DO_QAQC.r
```{r}
## all ##
dat <- read.csv("/Users/kellyloria/Documents/LittoralMetabModeling/Step1_LakeMetab_Processed/23_NS_Inputs.csv", header=T) 

dat1 <- dat %>% 
  mutate(datetime = as.POSIXct(datetime, format ="%Y-%m-%dT%H:%M:%OS")) %>%
  with_tz(tz = "America/Los_Angeles")

```

Temporary block to subset out certain chunks
```{r}
dat2 <- dat1 %>%
  filter(Site=="SSNS1" & year =="2023")

range(dat2$datetime) 
# "2023-01-01 14:00:00 PST" "2023-02-25 17:00:00 PST"

```

Function to get gas exchange estimates
```{r}
## Estimate gas exchange
data_K_estimate <- function(dat){

  # convert datetime to posixct
  dat$datetime <- as.POSIXct(as.character(dat$datetime), format="%Y-%m-%d %H:%M:%S")
  
  # subset dates
  data <- dat %>% 
   # filter(year == 2021 & yday >= 182 & yday <=273)  %>%  #
    drop_na()
  
  # assume complete mix at 3 meters
  data$z<- c(3)
  
  ## rename certain columns, do.obs to do, wtr to wtemp
  colnames(data)[which(colnames(data) == "do.obs")] <- "do"
  colnames(data)[which(colnames(data) == "wtr")] <- "wtemp"
  
  # further clean data to avoid zmix issues
  data <- data %>% 
    dplyr::group_by(year,yday) %>%
    mutate(obs = sum(!is.na(do))) %>% #identify and filter records that have < 23 hrs of data 
    dplyr::ungroup() %>%
    mutate(z = ifelse(z<=0.5,.5,z))%>% #can't have zero depth zmix
    mutate(z = ifelse(z>=3,3,z)) #in littoral zone depth zmix can not be deeper than the littoral depth
  
  # determine data frequency obs/day should be 24
  freq <- nrlmetab::calc.freq(data$datetime) 
  
  # estimate gas exchange
  data <- data %>% 
    mutate(k600 = k.vachon.base(wnd = wspeed,lake.area = 496000)) %>% #estimate K in m/day
    mutate(kgas = k600.2.kGAS.base(k600 = k600,temperature = wtemp,gas = "O2")) %>%  #m/d
    mutate(k = (kgas/freq)/z) %>% #convert gas to T^-1
    select(-kgas,-k600,-obs)
  
  # Assume no DO exchange with the Atmosphere. All DO change is related to metabolism
  data_k <- data %>% 
    mutate(k = ifelse(z<3,0,k))
  
  return(data_k)
  
}
```

```{r}
dat_K <- data_K_estimate(dat2)
# quick visualization:
ggplot(data=dat_K,aes(x=yday,y=do)) + geom_line() + facet_wrap(vars(year, Site),scales="free_x") +
  geom_point(aes(x=yday,y=z),col="blue",size=0.2)
```

Prepare for data analysis
```{r}
prep_data_for_LM <- function(data){
  
  data$hour <- lubridate::hour(data$datetime)

  sonde_prep <- data %>%
    arrange(Site, year, yday, hour) %>%
    # for each year, create identifier for uninterrupted stretches of observations
    group_by(year) %>%
    mutate(i = ifelse(is.na(do)==T, 1, 0), 
           j = c(1,abs(diff(i)))) %>% 
    filter(is.na(do)==F) %>%
    mutate(series = cumsum(j)) %>% 
    ungroup() %>%
    # create unique index for each series
    # remove series with fewer than 24 observations
    mutate(unique_series = year + series/length(unique(series))) %>%
    group_by(unique_series) %>%
    mutate(series_length = length(unique_series)) %>%
    ungroup() %>%
    # recreate series index and make unique index for days
    # create index for observations (for joining later)
    # replace 0 par_int with smallest non-zero value
    mutate(unique_series = as.factor(unique_series) %>% as.numeric(),
           unique_day = paste(year, yday) %>% as.factor() %>% as.numeric(),
           index = 1:length(do),
           par_int = ifelse(par_int==0,0.00001, par_int)) %>%
    select(-i, -j) 
  
  # return missing observations for check
  sonde_check <- data %>% 
    tidyr::expand(year,yday,hour) %>%
    full_join(sonde_prep) %>%
    arrange(year,yday)
  
  sonde_check<- na.omit(sonde_check)
  range(sonde_check$datetime)
  
  return(sonde_check)
  
}
```


#****#
# DO NOT RUN 
TAKE 2 re-write for multiple site locations:
```{r}
# Check column names in sonde_check
# print(names(sonde_check))

# Update the code with the correct column name
prep_R_for_LM <- function(sonde_check, freq, site){
  
  # Check if the column "site" is present in sonde_check
  if (!"site" %in% names(sonde_check)) {
    stop("Column 'site' not found in sonde_check.")
  }
  
  # Define variables in the environment 
  o2_freq = freq
  o2_obs = 1000*sonde_check$do # Convert to mg m^-3
  o2_eq = 1000*sonde_check$do_eq # Convert to mg m^-3
  light = sonde_check$par_int
  temp = sonde_check$wtemp
  wspeed = sonde_check$wspeed
  k = sonde_check$k
  
  # Create a unique identifier for each combination of year and site
  sonde_check$year_site = paste(sonde_check$year, sonde_check$site, sep="_")
  
  days_per_year = array(c({sonde_check %>%
      group_by(year) %>%
      summarize(value = length(unique(unique_day)))}$value), dim = 1) #,dim = 1
  
  obs_per_series = array(c({sonde_check %>%
      group_by(unique_series) %>%
      summarize(value = length(unique_series))}$value))
  
  obs_per_day = array(c({sonde_check %>%
      group_by(unique_day) %>%
      summarize(value = length(unique_day))}$value)) 
  z = sonde_check$z
  n_obs = length(o2_obs)
  n_series = length(obs_per_series) 
  n_days = sum(days_per_year)
  n_years = length(unique(sonde_check$year))

  # Export as .R
  stan_rdump(c("o2_freq", "o2_obs", "o2_eq", "light", "temp", "wspeed", "obs_per_series", "days_per_year",
               "obs_per_day", "z", "k", "n_obs", "n_series", "n_days", "n_years"),
             file = paste("/Users/kellyloria/Documents/LittoralMetabModeling/Sondefiles/", site, "_sonde_list.R", sep = ""))
  
}

```

```{r}
# Example usage
result <- prep_data_for_LM(dat_K)
```


```{r}
## visualize
ggplot(result,aes(x=datetime,y=do)) + geom_point(size=0.2) +
  geom_line() + facet_wrap(vars(year,Site),scales="free_x")
```

Function to save data:
```{r}
#  write.csv(result, file = "/Users/kellyloria/Documents/LittoralMetabModeling/Sondefiles/sonde_prep_SSNS1_test23.csv", row.names = TRUE)

```



```{r}
prep_R_for_LM <- function(sonde_check, freq){
  
  # Define variables in the environment 
  o2_freq = freq
  o2_obs = 1000*sonde_check$do # Convert to mg m^-3
  o2_eq = 1000*sonde_check$do_eq # Convert to mg m^-3
  light = sonde_check$par_int
  temp = sonde_check$wtemp
  wspeed = sonde_check$wspeed
  k = sonde_check$k
  
  # Create a unique identifier for each combination of year and site
  sonde_check$site_year = paste(sonde_check$Site, sonde_check$year, sep="_")
  
  days_per_year = array(c({sonde_check %>%
      group_by(year) %>%
      summarize(value = length(unique(unique_day)))}$value), dim = 1) #,dim = 1
  
  obs_per_series = array(c({sonde_check %>%
      group_by(unique_series) %>%
      summarize(value = length(unique_series))}$value))
  
  obs_per_day = array(c({sonde_check %>%
      group_by(unique_day) %>%
      summarize(value = length(unique_day))}$value)) 
  z = sonde_check$z
  n_obs = length(o2_obs)
  n_series = length(obs_per_series) 
  n_days = sum(days_per_year)
  n_years = length(unique(sonde_check$year))

  # Export as .R for each unique Site
  unique_sites = unique(sonde_check$Site)
  for (site in unique_sites) {
    site_data = subset(sonde_check, Site == site)
    stan_rdump(c("o2_freq", "o2_obs", "o2_eq", "light", "temp", "wspeed", "obs_per_series", "days_per_year",
                 "obs_per_day", "z", "k", "n_obs", "n_series", "n_days", "n_years"),
               file = paste("/Users/kellyloria/Documents/LittoralMetabModeling/Sondefiles/", site, "23test_sonde_list.R", sep = ""))
  }
  
}

```

```{r}
# Example usage
prep_R_for_LM(sonde_check = result, freq = 24)
```




